name: Postman API

on: [push, workflow_dispatch]

jobs:
  test:
    name: Back Tests Postman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Check versions of Newman and Node
        run: |
          newman --version
          node --version

      - name: Install Newman-Reporter-HtmlExtra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Execute collection
        run: newman run QualityEagles[Jamile].postman_collection.json -g workspace.postman_globals.json -r --delay-request 1 --reporters cli,htmlextra --reporter-htmlextra-export report.html

      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: report.html

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    if: success()
    needs:
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://jamile-xavier.github.io/QualityEaglesT13_Postman/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: postman-report
          path: results/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
